# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Mobile/Phone number must be entered in the format: '+999999999'. Minimum 9 digits & up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='blood',
            name='blood_status',
            field=models.IntegerField(choices=[(0, 'Received'), (1, 'Tested'), (2, 'Stored'), (3, 'Donated')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.IntegerField(choices=[(0, 'O'), (1, 'A'), (2, 'B'), (3, 'AB')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Mobile/Phone number must be entered in the format: '+999999999'. Minimum 9 digits & up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
