# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodlinebank',
            name='postcode',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
