# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0002_auto_20171017_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodlineblood',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodline.BloodlineBank'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='donor_date',
            field=models.DateTimeField(verbose_name='donor date'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
