# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0003_auto_20171017_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodlinebank',
            name='address',
            field=models.CharField(blank=True, help_text='Put your address here, maximum 200 characters.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloodlinebank',
            name='name',
            field=models.CharField(help_text='Put the blood bank name here, maximum 80 characters.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodlinebank',
            name='phone',
            field=models.CharField(blank=True, help_text="Mobile/Phone number must be entered in the format: '+999999999'. Minimum 9 digits & up to 15 digits allowed.", max_length=15, validators=[django.core.validators.RegexValidator(message="Mobile/Phone number must be entered in the format: '+999999999'. Minimum 9 digits & up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='bloodlinebank',
            name='postcode',
            field=models.CharField(help_text='Postcode format: XXXX.', max_length=4),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='bank',
            field=models.ForeignKey(help_text='Choose which bank did the user donated their blood into.', on_delete=django.db.models.deletion.CASCADE, to='bloodline.BloodlineBank'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='blood_status',
            field=models.IntegerField(choices=[(0, 'Received'), (1, 'Tested'), (2, 'Stored'), (3, 'Donated')], default=0, help_text='Set the status of the donated blood.'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='donor_date',
            field=models.DateTimeField(help_text='Date format: DD/MM/YYYY.', verbose_name='donor date'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='user',
            field=models.ForeignKey(help_text='Choose which user donated their blood.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
