# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0004_auto_20171017_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodlineblood',
            name='donor_date',
            field=models.DateTimeField(help_text='Date & time format: DD/MM/YYYY HH:MM.', verbose_name='donor date'),
        ),
    ]
