# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodline', '0005_auto_20171017_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodlineblood',
            name='donation_choices',
            field=models.IntegerField(choices=[(0, 'Whole Blood'), (1, 'Plasma'), (2, 'Platelet')], default=0, help_text='Make sure you selected correct donation choice.'),
        ),
        migrations.AlterField(
            model_name='bloodlineblood',
            name='blood_status',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Received'), (2, 'Tested'), (3, 'Stored'), (4, 'Donated')], default=0, help_text='Set the status of the donated blood.'),
        ),
    ]
